config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks, only: [:index, :show, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index   
      @tasks = Task.all
    end

    def show
      @task = Task.find(params[:id])
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)
        if @task.save
          flash[:success] = "task successfully created"
          redirect_to @task
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])
        if @task.update(task_params)
          flash[:success] = "task was successfully updated"
          redirect_to @task
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end

    def destroy
        @task = Task.find(params[:id])
        if @task.destroy
            flash[:success] = 'Object was successfully deleted.'
            redirect_to tasks_path
        else
            flash[:error] = 'Something went wrong'
            redirect_to tasks_path
        end
    end
    
    
    
    
    private

    def task_params
        params.require(:task).permit(:title, :details, :completed)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul id="tasks">
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed %>
        <i class="fa fa-check-square-o"></i>
      <% else %>
        <i class="fa fa-square-o"></i>
      <% end %>
      <%= link_to task.title, task_path(task.id) %>
      ·
      <%= link_to task_path(task.id), method: :delete, data: { confirm: "Delete #{task.title}?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to Tasks", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to "Edit this task", edit_task_path(@task) %>
<br>
<%= link_to "Back to Tasks", tasks_path %>